# Site settings
title: The Hoick Dev Blog
email: adam@thehoick.com
description: > # this means to ignore newlines until "baseurl:"
  Developer Blog for Adam Sommer and friends.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devblog.thehoick.com" # the base hostname & protocol for your site
twitter_username: asommer
github_username:  asommer70

# Build settings
markdown: kramdown

kramdown:
  input: GFM
